# Generated by Django 4.2.3 on 2023-08-02 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo12app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default='1999-02-23'),
            preserve_default=False,
        ),
    ]
